/*
 * NewJFrame.java
 *
 * Created on 31 Jul 2015, PM 11:11
 */
package tik.tak.toe;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author  hp
 */
public class Home extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public Home() {
        initComponents();
        
        setVisiblePanel(profilePanel);
        setButtons();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel = new javax.swing.JPanel();
        panelName = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        profilePanel = new javax.swing.JPanel();
        profileLable = new javax.swing.JLabel();
        profileNameLable = new javax.swing.JLabel();
        PerformanceLable = new javax.swing.JLabel();
        newButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        renameButton = new javax.swing.JButton();
        profileComboBox = new javax.swing.JComboBox();
        yourProfile = new javax.swing.JLabel();
        yourPerformance = new javax.swing.JLabel();
        Select = new javax.swing.JButton();
        SinglePlayePanel = new javax.swing.JPanel();
        singlePlayerLable = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        Difficulty = new javax.swing.JButton();
        difficultyLable = new javax.swing.JLabel();
        Profiles = new javax.swing.JButton();
        MultiPlayer = new javax.swing.JButton();
        difficultyPic = new javax.swing.JLabel();
        boardPanel = new javax.swing.JPanel();
        cell0 = new javax.swing.JLabel();
        cell1 = new javax.swing.JLabel();
        cell2 = new javax.swing.JLabel();
        cell3 = new javax.swing.JLabel();
        cell4 = new javax.swing.JLabel();
        cell5 = new javax.swing.JLabel();
        cell6 = new javax.swing.JLabel();
        cell7 = new javax.swing.JLabel();
        cell8 = new javax.swing.JLabel();
        Restart = new javax.swing.JButton();
        statusLable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Leave = new javax.swing.JButton();
        MultiPlayerPanel = new javax.swing.JPanel();
        multiPlayerLable = new javax.swing.JLabel();
        startNewServer = new javax.swing.JButton();
        Join = new javax.swing.JButton();
        Profile2 = new javax.swing.JButton();
        SinglePlayer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        homePanel.setBackground(new java.awt.Color(51, 51, 51));

        panelName.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18));
        panelName.setForeground(new java.awt.Color(255, 255, 255));
        panelName.setText("Tik - Tak - Toe");

        profilePanel.setBackground(new java.awt.Color(51, 51, 51));
        profilePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        profileLable.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        profileLable.setForeground(new java.awt.Color(255, 255, 255));
        profileLable.setText("Select Your Proile");

        profileNameLable.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 16)); // NOI18N
        profileNameLable.setForeground(new java.awt.Color(255, 255, 255));
        profileNameLable.setText("Profile:");

        PerformanceLable.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 16)); // NOI18N
        PerformanceLable.setForeground(new java.awt.Color(255, 255, 255));
        PerformanceLable.setText("Performance: ");

        newButton.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 16)); // NOI18N
        newButton.setForeground(new java.awt.Color(255, 255, 255));
        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 16)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete");

        renameButton.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 16)); // NOI18N
        renameButton.setForeground(new java.awt.Color(255, 255, 255));
        renameButton.setText("Rename");

        profileComboBox.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 16)); // NOI18N
        profileComboBox.setForeground(new java.awt.Color(51, 0, 204));
        profileComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        yourProfile.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 16)); // NOI18N
        yourProfile.setForeground(new java.awt.Color(255, 255, 255));

        yourPerformance.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 16)); // NOI18N
        yourPerformance.setForeground(new java.awt.Color(255, 255, 255));

        Select.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 16)); // NOI18N
        Select.setForeground(new java.awt.Color(255, 255, 255));
        Select.setText("Select");
        Select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(Select)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteButton)
                        .addGap(10, 10, 10)
                        .addComponent(renameButton))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profileLable, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addComponent(profileComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(profilePanelLayout.createSequentialGroup()
                                        .addComponent(profileNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(yourProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(profilePanelLayout.createSequentialGroup()
                                        .addComponent(PerformanceLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yourPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(profileLable, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profileNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yourProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PerformanceLable, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yourPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(renameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Select, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        profilePanel.setBounds(0, 0, 500, 390);
        jLayeredPane1.add(profilePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        SinglePlayePanel.setBackground(new java.awt.Color(51, 51, 51));
        SinglePlayePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        singlePlayerLable.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        singlePlayerLable.setForeground(new java.awt.Color(255, 255, 255));
        singlePlayerLable.setText("Single Player");

        start.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 16)); // NOI18N
        start.setForeground(new java.awt.Color(255, 255, 255));
        start.setText("Start");
        start.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        Difficulty.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 16)); // NOI18N
        Difficulty.setForeground(new java.awt.Color(255, 255, 255));
        Difficulty.setText("Difficulty");
        Difficulty.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        difficultyLable.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        difficultyLable.setForeground(new java.awt.Color(255, 255, 255));

        Profiles.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 16)); // NOI18N
        Profiles.setForeground(new java.awt.Color(255, 255, 255));
        Profiles.setText("Profiles");
        Profiles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Profiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfilesActionPerformed(evt);
            }
        });

        MultiPlayer.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 16)); // NOI18N
        MultiPlayer.setForeground(new java.awt.Color(255, 255, 255));
        MultiPlayer.setText("Multi Player");
        MultiPlayer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MultiPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiPlayerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SinglePlayePanelLayout = new javax.swing.GroupLayout(SinglePlayePanel);
        SinglePlayePanel.setLayout(SinglePlayePanelLayout);
        SinglePlayePanelLayout.setHorizontalGroup(
            SinglePlayePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SinglePlayePanelLayout.createSequentialGroup()
                .addGroup(SinglePlayePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SinglePlayePanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(singlePlayerLable, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SinglePlayePanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(SinglePlayePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MultiPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Profiles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Difficulty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(start, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(SinglePlayePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(difficultyPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(difficultyLable, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        SinglePlayePanelLayout.setVerticalGroup(
            SinglePlayePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SinglePlayePanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(singlePlayerLable, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SinglePlayePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(difficultyLable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Difficulty, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SinglePlayePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(difficultyPic, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SinglePlayePanelLayout.createSequentialGroup()
                        .addComponent(Profiles, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MultiPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        SinglePlayePanel.setBounds(0, 0, 500, 390);
        jLayeredPane1.add(SinglePlayePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        boardPanel.setBackground(new java.awt.Color(51, 51, 51));
        boardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        boardPanel.setForeground(new java.awt.Color(255, 255, 255));

        cell0.setBackground(new java.awt.Color(153, 153, 153));
        cell0.setForeground(new java.awt.Color(204, 204, 204));
        cell0.setToolTipText("");
        cell0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

        cell1.setBackground(new java.awt.Color(153, 153, 153));
        cell1.setForeground(new java.awt.Color(204, 204, 204));
        cell1.setToolTipText("");
        cell1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

        cell2.setBackground(new java.awt.Color(153, 153, 153));
        cell2.setForeground(new java.awt.Color(204, 204, 204));
        cell2.setToolTipText("");
        cell2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

        cell3.setBackground(new java.awt.Color(153, 153, 153));
        cell3.setForeground(new java.awt.Color(204, 204, 204));
        cell3.setToolTipText("");
        cell3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

        cell4.setBackground(new java.awt.Color(153, 153, 153));
        cell4.setForeground(new java.awt.Color(204, 204, 204));
        cell4.setToolTipText("");
        cell4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

        cell5.setBackground(new java.awt.Color(153, 153, 153));
        cell5.setForeground(new java.awt.Color(204, 204, 204));
        cell5.setToolTipText("");
        cell5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

        cell6.setBackground(new java.awt.Color(153, 153, 153));
        cell6.setForeground(new java.awt.Color(204, 204, 204));
        cell6.setToolTipText("");
        cell6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

        cell7.setBackground(new java.awt.Color(153, 153, 153));
        cell7.setForeground(new java.awt.Color(204, 204, 204));
        cell7.setToolTipText("");
        cell7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

        cell8.setBackground(new java.awt.Color(153, 153, 153));
        cell8.setForeground(new java.awt.Color(204, 204, 204));
        cell8.setToolTipText("");
        cell8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

        Restart.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        Restart.setForeground(new java.awt.Color(255, 255, 255));
        Restart.setText("Restsrt");

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        Leave.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 16)); // NOI18N
        Leave.setForeground(new java.awt.Color(255, 255, 255));
        Leave.setText("Leave");
        Leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boardPanelLayout = new javax.swing.GroupLayout(boardPanel);
        boardPanel.setLayout(boardPanelLayout);
        boardPanelLayout.setHorizontalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boardPanelLayout.createSequentialGroup()
                        .addComponent(Restart, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Leave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardPanelLayout.createSequentialGroup()
                        .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(boardPanelLayout.createSequentialGroup()
                                .addComponent(cell6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cell7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cell8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(boardPanelLayout.createSequentialGroup()
                                .addComponent(cell3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cell4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cell5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(boardPanelLayout.createSequentialGroup()
                                .addComponent(cell0, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cell1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cell2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statusLable, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        boardPanelLayout.setVerticalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardPanelLayout.createSequentialGroup()
                .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, boardPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(statusLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, boardPanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cell2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cell1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cell0, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cell3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cell4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cell5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cell6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cell7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cell8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Restart, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Leave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        boardPanel.setBounds(0, 0, 500, 390);
        jLayeredPane1.add(boardPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        MultiPlayerPanel.setBackground(new java.awt.Color(51, 51, 51));
        MultiPlayerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        multiPlayerLable.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 16)); // NOI18N
        multiPlayerLable.setForeground(new java.awt.Color(255, 255, 255));
        multiPlayerLable.setText("Multi Player");

        startNewServer.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 16)); // NOI18N
        startNewServer.setForeground(new java.awt.Color(255, 255, 255));
        startNewServer.setText("Start  New Server");
        startNewServer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        Join.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 16)); // NOI18N
        Join.setForeground(new java.awt.Color(255, 255, 255));
        Join.setText("Join");
        Join.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        Profile2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 16)); // NOI18N
        Profile2.setForeground(new java.awt.Color(255, 255, 255));
        Profile2.setText("Profiles");
        Profile2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Profile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile2ActionPerformed(evt);
            }
        });

        SinglePlayer.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 16)); // NOI18N
        SinglePlayer.setForeground(new java.awt.Color(255, 255, 255));
        SinglePlayer.setText("SinglePlayer");
        SinglePlayer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SinglePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinglePlayerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MultiPlayerPanelLayout = new javax.swing.GroupLayout(MultiPlayerPanel);
        MultiPlayerPanel.setLayout(MultiPlayerPanelLayout);
        MultiPlayerPanelLayout.setHorizontalGroup(
            MultiPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MultiPlayerPanelLayout.createSequentialGroup()
                .addGroup(MultiPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MultiPlayerPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(multiPlayerLable, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MultiPlayerPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(MultiPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Join, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(startNewServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Profile2, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(SinglePlayer, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        MultiPlayerPanelLayout.setVerticalGroup(
            MultiPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MultiPlayerPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(multiPlayerLable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(startNewServer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Join, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Profile2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SinglePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        MultiPlayerPanel.setBounds(0, 0, 500, 390);
        jLayeredPane1.add(MultiPlayerPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(panelName, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setVisiblePanel(JPanel panel){
        profilePanel.setVisible(false);
        SinglePlayePanel.setVisible(false);
        MultiPlayerPanel.setVisible(false);
        boardPanel.setVisible(false);
        
        panel.setVisible(true);
    }
    
    public void setButtons(){
        setButtonOpaque(Difficulty);
        setButtonOpaque(Join);
        setButtonOpaque(MultiPlayer);
        setButtonOpaque(Profiles);
        setButtonOpaque(Profile2);
        setButtonOpaque(SinglePlayer);
        setButtonOpaque(deleteButton);
        setButtonOpaque(Restart);
        setButtonOpaque(newButton);
        setButtonOpaque(startNewServer);
        setButtonOpaque(start);
        setButtonOpaque(renameButton);
        setButtonOpaque(Select);
        setButtonOpaque(Leave);
    }
    
    public void setButtonOpaque(JButton button){
        button.setOpaque(false);
        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
    }
    
private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_newButtonActionPerformed

private void SelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectActionPerformed
    setVisiblePanel(SinglePlayePanel);
}//GEN-LAST:event_SelectActionPerformed

private void ProfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfilesActionPerformed
    setVisiblePanel(profilePanel);
}//GEN-LAST:event_ProfilesActionPerformed

private void MultiPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiPlayerActionPerformed
    setVisiblePanel(MultiPlayerPanel);
}//GEN-LAST:event_MultiPlayerActionPerformed

private void LeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaveActionPerformed
    setVisiblePanel(SinglePlayePanel);
}//GEN-LAST:event_LeaveActionPerformed

private void Profile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile2ActionPerformed
    setVisiblePanel(profilePanel);
}//GEN-LAST:event_Profile2ActionPerformed

private void SinglePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinglePlayerActionPerformed
    setVisiblePanel(SinglePlayePanel);
}//GEN-LAST:event_SinglePlayerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Difficulty;
    private javax.swing.JButton Join;
    private javax.swing.JButton Leave;
    private javax.swing.JButton MultiPlayer;
    private javax.swing.JPanel MultiPlayerPanel;
    private javax.swing.JLabel PerformanceLable;
    private javax.swing.JButton Profile2;
    private javax.swing.JButton Profiles;
    private javax.swing.JButton Restart;
    private javax.swing.JButton Select;
    private javax.swing.JPanel SinglePlayePanel;
    private javax.swing.JButton SinglePlayer;
    private javax.swing.JPanel boardPanel;
    private javax.swing.JLabel cell0;
    private javax.swing.JLabel cell1;
    private javax.swing.JLabel cell2;
    private javax.swing.JLabel cell3;
    private javax.swing.JLabel cell4;
    private javax.swing.JLabel cell5;
    private javax.swing.JLabel cell6;
    private javax.swing.JLabel cell7;
    private javax.swing.JLabel cell8;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel difficultyLable;
    private javax.swing.JLabel difficultyPic;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel multiPlayerLable;
    private javax.swing.JButton newButton;
    private javax.swing.JLabel panelName;
    private javax.swing.JComboBox profileComboBox;
    private javax.swing.JLabel profileLable;
    private javax.swing.JLabel profileNameLable;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JButton renameButton;
    private javax.swing.JLabel singlePlayerLable;
    private javax.swing.JButton start;
    private javax.swing.JButton startNewServer;
    private javax.swing.JLabel statusLable;
    private javax.swing.JLabel yourPerformance;
    private javax.swing.JLabel yourProfile;
    // End of variables declaration//GEN-END:variables
}
